### ISSUE TITLE
Maintenance - May 2021

### ISSUE THREAD

**Issue by SMerdzhanov** [MK-IT/gatsby-theme-password-protect#3]
This project hasn't been maintained for a while. 

Although quite simple, it gets the job done so it we want to bring it up to speed with the latest Gatsby trends overall DX improvements.

**TODO**

- [ ] Add the appropriate `.vscode` configurations similar to [gatsby-starter-essentials](https://github.com/MK-IT/gatsby-starter-essentials) repository
- [ ] Update all packages
- [ ] Upgrade all packages
- [ ] Check `.editorconfig` and update if needed
- [ ] Check `.npmignore` and update if needed
- [ ] Check `.gitignore` and update if needed
- [ ] Check `.eslintrc.js` and update if needed
- [ ] Check `.prettierrc.js` and update if needed
- [ ] Check `.release-it.js` and update if needed
- [ ] Check `.gatsby-*.js` files and update if needed
- [ ] Implement Conventional Commits
- [ ] Implement Husky with `pre-commit` and `commit-msg` hooks
- [ ] Use Yarn instead of npm and move to `yarn.lock` instead of `package-lock`
- [ ] Update `README.md` to match the style of [gatsby-starter-essentials](https://github.com/MK-IT/gatsby-starter-essentials) repository
- [ ] Update `ROADMAP.md` to highlight our intentions for improvements
- [ ] Release a new version to npm
